### ISSUE TITLE
Running behind a reverse proxy?

### ISSUE THREAD

**Issue by xme** [thalesgroup-cert/Watcher#14]
Not a feature request/bug but advice...
Anybody is already running Watcher behind a reverse-proxy (traefik in my case)? 
In the official docker-compose file, IP addresses are assigned to the containers. My idea is to connect the 'watcher' container also to my traefik network to be accessed by the reverse proxy.

**Comment by JamesCullum** [comment]
The IP addresses assigned are docker internal, not on your network (proper use is hostnames instead of IPs). Docker will expose the named ports on the host device, to which you need to map your reverse proxy.

**Comment by 8ear** [comment]
Hi,
I use traefik as reverse proxy for watcher: https://github.com/it-bgk/cdc-plattform/blob/master/watcher/docker-compose.override.yml
