### ISSUE TITLE
Alternative DNS servers?

### ISSUE THREAD

**Issue by xme** [thalesgroup-cert/Watcher#24]
It's not a bug report not a feature request but a question...
I'm using specific DNS resolvers with my containers. However, due to the huge amount of requests performed by Watcher, I'd like to use alternative DNS resolvers to not flood the current ones.
I presume that the container called 'watcher' is the one that generates most of the DNS requests right?
Happy Holidays!

**Comment by Felix83000** [comment]
Hi,

Most of the DNS requests are generated by 'watcher's container (website monitoring & dnstwist algorithm).

However, 'searx', 'searx-checker' and 'rss-bridge' containers also do DNS queries.

Happy New Year !
