### ISSUE TITLE
Scrape error Watcher

### ISSUE THREAD

**Issue by m1chas** [thalesgroup-cert/Watcher#34]
I am getting this output when watcher is scraping for dataleaks.

watcher          | 2021-04-19 22:50:08.063406 -  HTTPSConnectionPool(host='10.10.10.3', port=8080): Max retries exceeded with url: /search?q=%22xxxxx%22&engines=gitlab%2Cgithub%2Cbitbucket%2Capkmirror%2Cgentoo%2Cnpm%2Cstackoverflow%2Choogle&format=json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

**Comment by Felix83000** [comment]
Hi,

Do you get this output for all requests ?
Or just one or two?

Regards,

**Comment by m1chas** [comment]
Hi,

I get the output for all requests (except pastebin which gives the pro warning in addition).

Thank you,

**Comment by Felix83000** [comment]
I will check why this happened and come back to you this week.

Regards,

**Comment by m1chas** [comment]
thank you very much.
(love the app btw)

**Comment by Felix83000** [comment]
It is due to a major change with the new Searx version...
Please use the new `docker-compose.yml`. (https://github.com/thalesgroup-cert/Watcher/blob/master/docker-compose.yml)

**Comment by Felix83000** [comment]
Please tell me if it worked.

Regards,

**Comment by m1chas** [comment]
nope, exactly the same error. sorry.

did a complete reinstall.

**Comment by Felix83000** [comment]
Please follow these steps:
```
docker-compose down
docker rmi searx/searx
```
In the `docker-compose.yml` file change `image: searx/searx:latest` by `image: searx/searx:0.18.0-341-ae0b621e`

Be sure that your `settings.yml` is exactly the same than this one: https://www.github.com/thalesgroup-cert/Watcher/tree/master/Searx%2Fsearx%2Fsettings.yml

```
docker-compose up
```
It worked on my side, I hope it will work on your side. Keep me posted.

**Comment by m1chas** [comment]
hey Felix, tks! It works now.

**Comment by Felix83000** [comment]
Thank YOU for reporting this issue! 👍
