### ISSUE TITLE
Word Cloud and Trendy Words are not populating

### ISSUE THREAD

**Issue by HoneySsharma** [thalesgroup-cert/Watcher#47]
**Describe the bug**
Word Cloud and Trendy Words on Home Page is not populated ( it never did)

**To Reproduce**
1. Go to 'www.localhost.com:9002'
2. Click on 'Watcher icon (Home Page)'

**Expected behavior**
Expectation to see Word Cloud and Trendy Words on home page

**Desktop (please complete the following information):**
 - OS: Centos7
 - Browser : Firefox
 - Version : fresh install visa docker compose

**Additional context**
Did a fresh installation via docker compose. Perform migration and populate DB steps and did docker-compose up. Still word cloud and trendy words were not populating (waited for hours). In Logs, the API of Trendy words is giving response code of 200.

**Comment by Felix83000** [comment]
Hi,

If you are using Watcher through a proxy, you need to be sure that these urls are accessible https://abs.twimg.com and https://api.twitter.com from the RSS-Bridge container. If not, Watcher will not able to get the data from Twitter and Word Cloud and Trendy Words will remain empty. Hence, you will need to whitelist these urls.

If your are not using Watcher through a proxy please verify that RSS-Bridge is working (You can check RSS-Bridge docker-compose logs). If not, Word Cloud and Trendy Words will remain empty.

Sincerely,

**Comment by HoneySsharma** [comment]
Thanks it is populating now.
