### ISSUE TITLE
Error response from daemon: pull access denied for searx/searx-checker, repository does not exist

### ISSUE THREAD

**Issue by sanvu88** [thalesgroup-cert/Watcher#50]
Error response from daemon: pull access denied for searx/searx-checker, repository does not exist

https://prnt.sc/1qx6deq

**Comment by yud121212** [comment]
maybe build image on host with https://github.com/searx/searx-checker

**Comment by Felix83000** [comment]
Hi, 

Searx-checker is taken out of service. It wasn't essential for Watcher. We'll remove it from the docker-compose.yml file.

Best regards
