### ISSUE TITLE
searx-checker: The image for the service you're trying to recreate has been removed.

### ISSUE THREAD

**Issue by dagobertdebug** [thalesgroup-cert/Watcher#51]
**Describe the bug**
Pulling searx-checker (searx/searx-checker:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.
Continue with the new image? [yN]y
Pulling searx-checker (searx/searx-checker:)...
ERROR: pull access denied for searx/searx-checker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**To Reproduce**
docker-compose up -d

**Comment by Felix83000** [comment]
Hello,

It has been explained and fixed in this issue: #50.

**Comment by dagobertdebug** [comment]
Thanks.
