### ISSUE TITLE
 Watcher does not respond to the configuration change for the host address in the .env file.

### ISSUE THREAD

**Issue by Ral-A** [thalesgroup-cert/Watcher#54]
**Describe the bug**
Hello, I don't know if it is a general bug, or a particular  case; but when starting the Watcher containers, the application server is initialized with the address http://0.0.0.0:9002/ by default.
However, the installation guide refers that it can be modified, placing the new address in the "ALLOWED_HOST =" section of the .env file; then run the commands:
docker-compose down
docker-compose up
When performing these actions, the Watcher server continues to raise with the default address.
In the same way the changes are not applied when the mail server is configured.

**Screenshots**
Address after changing in config file .env:
![image](https://user-images.githubusercontent.com/94180676/141492383-c992139e-6dd6-4726-a35b-6b379c63fcdb.png)

![image](https://user-images.githubusercontent.com/94180676/141491064-f98b329c-161a-4384-a800-ecae812e8cb4.png)
Docker version on which it runs:
![image](https://user-images.githubusercontent.com/94180676/141492765-b0b902ec-688a-4597-82e9-f0e58954feec.png)

**Desktop (please complete the following information):**
 - OS: CentOS 8
 - Browser Firefox
 - Version CentOS Linux release 8.4.2105

Please I accept any recomendation to solve this problem.
Thanks

**Comment by Felix83000** [comment]
Hello Ral-A,

There is no issue.
0.0.0.0 is totally normal. It means that Watcher container will **use your server IP address**. 
For instance, if your server IP is **172.3.X.X** Watcher will be available at **http://172.3.X.X:9002**

In the meantime, you need to set the **ALLOWED_HOST** to your server IP address or FQDN, for instance **172.3.X.X**
This settings is necessary to prevent security issues. 

For the SMTP server, please check manually that the Watcher server can access it. (e.g. curl)

I hope it helps.

Regards,
