### ISSUE TITLE
Question: Monitor for information leaks -> what sources?

### ISSUE THREAD

**Issue by dagobertdebug** [thalesgroup-cert/Watcher#67]
Hi

Please allow me to ask the following questions:

- What exact information sources are being checked for the Data Leak feature? It says "Monitor for information leaks, for example in Pastebin & other IT content exchange websites (stackoverflow, github, gitlab, bitbucket, apkmirror, npm...)." What is the exact list and where to find it?

- And is it possible to add/remove sources? If yes, how?

Thank you very much for this tool and your response!

Dago

**Comment by Felix83000** [comment]
Hello,

_What exact information sources are being checked for the Data Leak feature? It says "Monitor for information leaks, for example in Pastebin & other IT content exchange websites (stackoverflow, github, gitlab, bitbucket, apkmirror, npm...)." What is the exact list and where to find it?_
**The exact list is here: https://github.com/thalesgroup-cert/Watcher/blob/master/Watcher/Watcher/threats_watcher/datas/sources.csv**


_And is it possible to add/remove sources? If yes, how?_
**Please check the documentation here:**
https://thalesgroup-cert.github.io/Watcher/README.html#add-your-rss-source-to-threats-detection

All of it is explained.

Best regards.

**Comment by dagobertdebug** [comment]
@Felix83000 thanks for your response. Sorry if I was not clear, I'll try it again:

There is menu "Data Leak" and one can specify "Keywords Monitored" that raise "Alerts". 

What sources are monitored for that keywords?

Thanks,
Dago

**Comment by Felix83000** [comment]
Hello,

Sure, for this part we are using Searx.
And we are using these search engines:
 
 'engines'​: 'gitlab,github,bitbucket,apkmirror,gentoo,npm,stackoverflow,hoogle'​,

Best regards
