### ISSUE TITLE
Question: Move to 7/7 days and 24/24h

### ISSUE THREAD

**Issue by sephirothac** [thalesgroup-cert/Watcher#70]
Hello,

Thank you for your project, please I would like to have if possible how to change the main_watch from 7/7 days and 24h/24h for the update of words

main_watch (trigger: cron[day_of_week='mon-fri', hour='7-18', minute='*/30'], next run at: 2022-04-25 15:00:00 CEST)" raised an exception

Thank you very much for your work.

**Comment by Felix83000** [comment]
Hello sephirothac,

It is planned to add the possibility to modify that in the settings. We will try to add that in the next release.

Sincerely,
Félix

**Comment by sephirothac** [comment]
Hello [Felix83000](https://github.com/Felix83000), 

Thank you very much for your feedback, can't wait to see what happens next, thanks for your work.

Sincerely Sephirothac.
