### ISSUE TITLE
MySQLdb._exceptions.OperationalError: Illegal mix of collations 

### ISSUE THREAD

**Issue by sephirothac** [thalesgroup-cert/Watcher#74]
**Describe the bug**
Hello, thank you for your fix for the 7/7 and 24/24 it is functional but since the update I have log returns.

Thank you very much for your help.

**To Reproduce**
>docker-compose rm watcher
>docker pull felix83000/watcher:latest
>docker-compose run watcher bash
>python manage.py migrate
>exit
>docker-compose up -d

**Log**
today at 15:25:39Job "main_watch (trigger: cron[day_of_week='mon-sun', minute='*/30'], next run at: 2022-05-14 15:30:00 CEST)" raised an exception
today at 15:25:39Traceback (most recent call last):
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
today at 15:25:39    return self.cursor.execute(sql, params)
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
today at 15:25:39    return self.cursor.execute(query, args)
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
today at 15:25:39    res = self._query(query)
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
today at 15:25:39    db.query(q)
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
today at 15:25:39    _mysql.connection.query(self, query)
today at 15:25:39MySQLdb._exceptions.OperationalError: (1267, "Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")
today at 15:25:39
today at 15:25:39The above exception was the direct cause of the following exception:
today at 15:25:39
today at 15:25:39Traceback (most recent call last):
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
today at 15:25:39    retval = job.func(*job.args, **job.kwargs)
today at 15:25:39  File "/app/Watcher/threats_watcher/core.py", line 76, in main_watch
today at 15:25:39    focus_on_top(settings.WORDS_OCCURRENCE)
today at 15:25:39  File "/app/Watcher/threats_watcher/core.py", line 216, in focus_on_top
today at 15:25:39    if TrendyWord.objects.filter(name=word):
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 324, in __bool__
today at 15:25:39    self._fetch_all()
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1507, in _fetch_all
today at 15:25:39    self._result_cache = list(self._iterable_class(self))
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
today at 15:25:39    results = compiler.execute_sql(
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
today at 15:25:39    cursor.execute(sql, params)
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
today at 15:25:39    return self._execute_with_wrappers(
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
today at 15:25:39    return executor(sql, params, many, context)
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
today at 15:25:39    return self.cursor.execute(sql, params)
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
today at 15:25:39    raise dj_exc_value.with_traceback(traceback) from exc_value
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
today at 15:25:39    return self.cursor.execute(sql, params)
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
today at 15:25:39    return self.cursor.execute(query, args)
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
today at 15:25:39    res = self._query(query)
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
today at 15:25:39    db.query(q)
today at 15:25:39  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
today at 15:25:39    _mysql.connection.query(self, query)
today at 15:25:39django.db.utils.OperationalError: (1267, "Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")

**Comment by Felix83000** [comment]
Hello,

I try to fix it next week.

Best regards,
Félix

**Comment by Felix83000** [comment]
Hello sephirothac,

Can you tell me your MySQL docker image version?

Thanks

**Comment by Felix83000** [comment]
Hello

**Comment by sephirothac** [comment]
Hello Felix83000, 

No return of log (MySQLdb._exceptions.OperationalError: Illegal mix of collations) since 1h for me the problem is solved, thanks for your help.

Sincerely sephirothac
